### PR TITLE
build(telemetry): Release 0.3.1

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

Release kedro-telemetry 0.3.1

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the relevant `RELEASE.md` file
- [x] Added tests to cover my changes

### CODE REVIEW

**Review by merelcht — APPROVED** [review]
🥳

**Review by ankatiyar — APPROVED** [review]
🚀

**Review by AhdraMeraliQB — APPROVED** [review]
⭐

**Review by DimedS — APPROVED** [review]
👍

**Pull request merged**
