### PR TITLE
fix(datasets): Refactor TensorFlowModelDataset to DataSet

### PR DESCRIPTION
**Pull request by BrianCechmanek**
Matching consistency of all other kedro-datasets, DataSet should be camelcase. 

It will be reverted in 0.19.0 per [#2129](https://github.com/kedro-org/kedro/issues/2129).

## Description
See previous discussion [#2494](https://github.com/kedro-org/kedro/issues/2494). 

All other supported DataSets have are camelcased (upper S). 

## Development notes

This refactors all instances of `TensorFlowModelDataset` to `TensorFlowModelDataSet`. 
There are also some instances of `TensorflowModelDataset`, looking into if those should be changed as well (tbd)

I couldn't run the test suite to verify - I will investigate that later. 

## Checklist

- [X] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by deepyaman — APPROVED** [review]
LGTM

**Review by noklam — APPROVED** [review]
Looks good to me, maybe add this in the release note? I consider this as a bug fix.

**Comment by BrianCechmanek** [comment]
Thanks both! 

@noklam, not sure if you meant for me specifically to add a comment to the `RELEASE.md`.. Wasn't quite sure format, so I just guessed. Please feel free to fix/reject. 

**Note**: I couldn't get any of the commands in the makefile working, specifically to build and/or test this PR locally. I'll try and look into this next.

**Comment by noklam** [comment]
@BrianCechmanek Yes, that's great. I have made a few more changes in the doc and I am merging it now! Thanks

**Pull request merged**
