### PR TITLE
Replace kedro.pipeline with modular_pipeline.pipeline factory

### PR DESCRIPTION
**Pull request by adamfrly**
Replace kedro.pipeline.Pipeline with
kedro.pipeline.modular_pipeline.pipeline factory.
This is for symmetry with changes made to the main kedro library.

Signed-off-by: Adam Farley <adamfrly@gmail.com>

## Description

The tests in the main kedro repo's test suite are being changed to use the `pipeline.modular_pipeline.pipeline` factory to create `kedro.pipeline.Pipeline` and `kedro.pipeline.pipeline` objects instead of instantiating the objects themselves directly. This PR is to provide symmetry in the kedro-plugins repo.

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the relevant `RELEASE.md` file
- [x] Added tests to cover my changes

### CODE REVIEW

**Comment by adamfrly** [comment]
The `win_unit_test` steps in the `airflow` plugin pipeline are running `make test-pipeline-no-spark` which hardcodes `cd kedro-datasets` guaranteeing the `dataset` plugin tests are being run. Consequently the unit tests are failing because the environment the tests are running in do not have the required libraries for the `kedro-dataset` tests to pass.

Could a potential fix be changing the `test-no-spark` make command to `cd $(plugin) && pytest tests --no-cov --ignore tests/spark --numprocesses 4 --dist loadfile` to match most of the other `make` commands?

**Comment by adamfrly** [comment]
@merelcht This is the PR similar to https://github.com/kedro-org/kedro/pull/2189 where I am replacing all instances in the test suite of `kedro.pipeline.pipeline` and `kedro.pipeline.Pipeline` with `kedro.pipeline.modular_pipeline.pipeline`.

I am running into some issues with circle_ci though. I know the unit-tests should pass, but the `win_unit_tests` are running the wrong test suites for the plugins that aren't the `dataset` plugin. I would appreciate your help on how to fix this😄

**Comment by merelcht** [comment]
> @merelcht This is the PR similar to [kedro-org/kedro#2189](https://github.com/kedro-org/kedro/pull/2189) where I am replacing all instances in the test suite of `kedro.pipeline.pipeline` and `kedro.pipeline.Pipeline` with `kedro.pipeline.modular_pipeline.pipeline`.
> 
> I am running into some issues with circle_ci though. I know the unit-tests should pass, but the `win_unit_tests` are running the wrong test suites for the plugins that aren't the `dataset` plugin. I would appreciate your help on how to fix this😄

Ahhh I see there's something wrong with the `CircleCI` setup here.. Let me play around with it and try to fix it!

**Comment by adamfrly** [comment]
@merelcht Sorry to be such a pain, but I think there are more errors in `win-tests` unrelated to my changes.

I think the `dataset` plugin failures should just be re-run and will be fine. But the `airflow` plugins are failing due to not hitting coverage requirements. It looks like line 11 in `kedro_ariflow\tests\test_plugin.py` is the culprit but this is a simple `identity` function that has no issues in similar test in the `telemetry` plugin. Happy to help in any way I can :)

**Comment by merelcht** [comment]
> @merelcht Sorry to be such a pain, but I think there are more errors in `win-tests` unrelated to my changes.
> 
> I think the `dataset` plugin failures should just be re-run and will be fine. But the `airflow` plugins are failing due to not hitting coverage requirements. It looks like line 11 in `kedro_ariflow\tests\test_plugin.py` is the culprit but this is a simple `identity` function that has no issues in similar test in the `telemetry` plugin. Happy to help in any way I can :)

Arghh so sorry for our clunky setup! These plugins are touched a lot less often than the main kedro repo, so they're not as up to date 😞 I've opened a PR https://github.com/kedro-org/kedro-plugins/pull/105 to fix this!

**Comment by adamfrly** [comment]
@merelcht No worries at all! Happy to be helping out 😄

**Comment by merelcht** [comment]
Hi @adamfrly, my fix https://github.com/kedro-org/kedro-plugins/pull/105 has now been merged! Can you try merge in `main` into your branch again and see if it's indeed solved the issue with the builds?

**Comment by adamfrly** [comment]
@merelcht Merged the new changes in and looks like the tests seem to be passing now! 🥳

**Review by merelcht — APPROVED** [review]
Thanks so much for this change @adamfrly ⭐ 

For consistency, let's also add this change to the release notes of `kedro-telemetry`, but other than that this looks good to me merged! 👍

**Review by jmholzer — APPROVED** [review]
Awesome, looks great. Thanks so much @adamfrly!

**Pull request merged**
