### PR TITLE
feat(datasets): Enable search-as-you type on Kedro-datasets docs

### PR DESCRIPTION
**Pull request by rashidakanchwala**
## Description

Enable search-as-you type on Kedro-viz docs. Also opens the search when you click on Ctrl+K

## Development notes

Basically copy/pasted the same javascript code from Kedro docs.

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by stichbury** [comment]
I couldn't see this to test it on the built preview https://kedro--532.org.readthedocs.build/projects/kedro-datasets/en/532/ ?

**Comment by astrojuanlu** [comment]
That requires us enabling the RTD add-ons to that repo, unfortunately. The only way to test this is to create a RTD project from a fork, commenting out a bunch of stuff that Heap needs, etc.

The alternative is to go full YOLO, push this to production, enable the add-ons, and if something doesn't work, fix it on the spot.

**Comment by rashidakanchwala** [comment]
Yeah, that's what I thought. Also because we kind of did the RTD testing on Kedro already and this is basically the exact code. I was thinking maybe we just go YOLO? @stichbury @astrojuanlu ?

**Comment by stichbury** [comment]
OK that's fine by me. Please just do the necessary to get it to pass the checks and we can merge it and see!

**Review by stichbury — APPROVED** [review]

**Review by astrojuanlu — APPROVED** [review]

**Pull request merged**
