### PR TITLE
ci: don't run checks on both `push`/`pull_request`

### PR DESCRIPTION
**Pull request by deepyaman**
## Description

If you see a PR like #189, you'll see jobs are being run on `push` and `pull_request` (instead of either-or).

image

Furthermore, the path filtering is a bit too aggressive, in that it won't consider changes to files like `.pre-commit-config.yaml`, etc. It may be a bit too conservative now, in that a change to `kedro-airflow.yaml` will trigger all the checks, but:

1. changing CI workflows is comparatively rare
2. ignoring folders is easier than including the plugin folder + an exhaustive list of files

Maybe we can just add the CI workflow definitions to `paths-ignore` as well. 

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by merelcht — COMMENTED** [review]
I noticed the duplicate CI runs! Thanks for changing it. 

I don't really understand why this change made it not run for both `push` and `pull_request` though 😅  Is it because you added the branch filter? 
I'm also wondering what did `types: [ synchronize ]` do before?

**Comment by deepyaman** [comment]
> I noticed the duplicate CI runs! Thanks for changing it.
> 
> I don't really understand why this change made it not run for both `push` and `pull_request` though 😅 Is it because you added the branch filter?

You want to run on both merge to `main` and pull requests against `main`.

> I'm also wondering what did `types: [ synchronize ]` do before?

There's a better description of `pull_request` types on https://frontside.com/blog/2020-05-26-github-actions-pull_request/ than on the actual docs. :) In short, it adds a trigger when commits are pushed to the branch. However, by default, it triggers on `pull_request` on `opened`, `repopened`, or `synchronize`, so this is more limiting (you'll need to explicitly trigger if not running on `push` and not opening a PR. In short, the changes make it so that it will only trigger CI on open PRs.

**Review by merelcht — APPROVED** [review]
Thanks @deepyaman ⭐

**Comment by SajidAlamQB** [comment]
> > I noticed the duplicate CI runs! Thanks for changing it.
> > I don't really understand why this change made it not run for both `push` and `pull_request` though 😅 Is it because you added the branch filter?
> 
> You want to run on both merge to `main` and pull requests against `main`.
> 
> > I'm also wondering what did `types: [ synchronize ]` do before?
> 
> There's a better description of `pull_request` types on https://frontside.com/blog/2020-05-26-github-actions-pull_request/ than on the actual docs. :) In short, it adds a trigger when commits are pushed to the branch. However, by default, it triggers on `pull_request` on `opened`, `repopened`, or `synchronize`, so this is more limiting (you'll need to explicitly trigger if not running on `push` and not opening a PR. In short, the changes make it so that it will only trigger CI on open PRs.

Without `synchronize` would that not mean it won't run CI when you update the `branch` PR with changes on `main`?

**Comment by deepyaman** [comment]
> > > I noticed the duplicate CI runs! Thanks for changing it.
> > > I don't really understand why this change made it not run for both `push` and `pull_request` though 😅 Is it because you added the branch filter?
> > 
> > 
> > You want to run on both merge to `main` and pull requests against `main`.
> > > I'm also wondering what did `types: [ synchronize ]` do before?
> > 
> > 
> > There's a better description of `pull_request` types on https://frontside.com/blog/2020-05-26-github-actions-pull_request/ than on the actual docs. :) In short, it adds a trigger when commits are pushed to the branch. However, by default, it triggers on `pull_request` on `opened`, `repopened`, or `synchronize`, so this is more limiting (you'll need to explicitly trigger if not running on `push` and not opening a PR. In short, the changes make it so that it will only trigger CI on open PRs.
> 
> Without `synchronize` would that not mean it won't run CI when you update the `branch` PR with changes on `main`?

As mentioned above in the reply you quoted, `synchronize` scope is included by default, together with `opened` and `reopened`. So it broadens the trigger types by removing `[ synchronize ]`.

**Comment by ankatiyar** [comment]
I was also trying to figure out a way to only run tests once - this seems like a good way! +1 on ignoring paths instead. The only thing I guess is that the tests won't run on your branch before you open a PR? I find it useful to have the tests passing/failing before/without opening a PR (prototyping something for eg) but I don't think that's a very big problem.

**Review by SajidAlamQB — APPROVED** [review]

**Pull request merged**
