### PR TITLE
fix(datasets): add metadata parameter to datasets

### PR DESCRIPTION
**Pull request by michal-mmm**
## Description
Fix issue: #699 

## Development notes
- added `metadata` to `__init__` of some datasets

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by ankatiyar — APPROVED** [review]
Thank you @michal-mmm! Good catch!

**Review by noklam — APPROVED** [review]

**Comment by datajoely** [comment]
Is there any reason that the `metadata` constructor argument isn't part of the `AbstractDataset` definition?

**Comment by datajoely** [comment]
lol same thought @noklam

**Comment by ankatiyar** [comment]
@noklam @datajoely https://github.com/kedro-org/kedro/issues/1076#issuecomment-1486867936
This is what I found 🤔

**Pull request merged**
