### PR TITLE
ci: Automatically extract release notes for GitHub Releases

### PR DESCRIPTION
**Pull request by ankatiyar**
## Description

To fully automate the release process, the release notes should be automatically generated. 
For the first iteration of the workflow, the body was simply "Release <version_number>"

## Development notes

* Added a python script to `tools/github_actions` which extracts the text section under the latest release heading from `<package_name>/RELEASE.md` 
* Use https://github.com/softprops/action-gh-release Action for automatic GitHub release step and use the extracted text as the body for the release note
* Tested this on my fork https://github.com/ankatiyar/kedro-plugins/releases
* Test the python script with `python extract_release_notes.py <filename> <heading>`

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by noklam — COMMENTED** [review]
Thanks, could it use the package version and match the section? From your test it seems that the Action is extracting the Upcoming release notes. 

For example if you are doing a release for kedro-docker 0.3.2
Then it should look for 
kedro-plugins/kedro-docker/release.md with a section Release 0.3.2

**Comment by ankatiyar** [comment]
> Thanks, could it use the package version and match the section? From your test it seems that the Action is extracting the Upcoming release notes.
> 
> For example if you are doing a release for kedro-docker 0.3.2 Then it should look for kedro-plugins/kedro-docker/release.md with a section Release 0.3.2

@noklam The python script receives the filename and the new package version as arguments and it extracts the section under "Release 0.3.2"(for example) since following the merge of the release PR the heading for the "Upcoming Release" would have changed to "Release 0.3.2" in the release notes.

**Comment by noklam** [comment]
@ankatiyar thanks for explaining! It might help if you can put the excerpt of the Release.md in the description.

**Review by noklam — APPROVED** [review]
Thanks! Just some minor comments, I test it locally and works great!

**Pull request merged**
