### PR TITLE
ci: ensure title matches Conventional Commits spec

### PR DESCRIPTION
**Pull request by deepyaman**
### Challenges

[...]

- It's not clear which changes affect which plugins
  - Denoted inconsistently using tags like `[kedro-docker]` on PR/issues (nonstandard solution)

### Proposal

[...]

- [ ] [P1] Enforce use of [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) with per-plugin scopes with [`commitlint`](https://github.com/conventional-changelog/commitlint) -- rough estimate: trivial, <0.5 days

_Originally posted by @deepyaman in https://github.com/kedro-org/kedro/issues/2333#issuecomment-1434492921_

## Development notes

Tested manually. Also, have used the Action on other projects previously. The configuration is pretty much that documented in the Action's repo.

Can somebody with rights ensure that the squash-merge strategy IS NOT set to use the commit message if there's only one commit? See https://github.com/amannn/action-semantic-pull-request#installation.

Is there (going to be) a CONTRIBUTING.md for this repo? If so, we can include the following:

### Pull request title conventions

The Kedro-Plugins repository requires that you [squash and merge your pull request commits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits), and, in most cases, the [merge message for a squash merge](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#merge-message-for-a-squash-merge) then defaults to the pull request title.

Your pull request title must match the [Conventional Commits spec](https://www.conventionalcommits.org/). Also see the [list of supported commit types and their descriptions](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js#L41-L99). Commit scope can be one of the plugin names.

##### Commit message with no body

`ci: port lint, unit test, and e2e tests to Actions`

##### Commit message with scope

```build(datasets): add the missing `snowflake` extra```

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by noklam** [comment]
👀How Is this gonna work does it reject invalid pr immediately?

**Comment by noklam** [comment]
Ah I guess it will be just another check, so it won't prevent people from opening invalid PR but just blocking the merge of it.

**Comment by deepyaman** [comment]
> Ah I guess it will be just another check, so it won't prevent people from opening invalid PR but just blocking the merge of it.
> 
> What is a valid PR title here?

Yes, correct. I would follow the Conventional Commits specification, with scope as one of airflow, datasets, docker, etc.

**Review by noklam — APPROVED** [review]
I checked to see if it's possible to have a PR title in the template, it doesn't seem to be possible. The rules are simple enough so I think it's ok.
https://github.com/isaacs/github/issues/1252

p.s. I think we should have a CONTRIBUTOR.md here.

**Comment by noklam** [comment]
> Yep! I didn't require a scope, because (like you pointed out) not all PRs will apply to just one plugin.

How are we dealing with it? I am seeing the checking failed for this PR

**Comment by deepyaman** [comment]
> > Yep! I didn't require a scope, because (like you pointed out) not all PRs will apply to just one plugin.
> 
> How are we dealing with it? I am seeing the checking failed for this PR

Where? I'm seeing it passed. 😅 I did modify it to "ci(invalid-scope): ensure title matches Conventional Commits spec" at some point before, so maybe the failure is associated with that?

**Review by ankatiyar — APPROVED** [review]
+1 on adding a `CONTRIBUTING.md` here but also might be worth adding a note in the PR template itself so people can see it when they open the PR - [like we did for kedro repository when we moved `kedro-datasets`](https://github.com/kedro-org/kedro/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

**Pull request merged**
