### PR TITLE
dtypes support when reading csv files into Polars

### PR DESCRIPTION
**Pull request by grofte**
## Description
Polars needs Polars dtypes, rather than strings, when reading a csv if you want to set the dtypes rather than depend on schema inference. So this takes a string argument like "pl.Int64" in a sequence or mapping and substitutes it with the actual pl.Int64. 

## Development notes
I've tested it in the spaceflights tutorial, both that it works and fails as expected and that it works for all three ways of loading a CSV into Polars. For CSVDataset and Eager I did a `.to_pandas()` in the first line processing `companies` and for Lazy I did `.collect().to_pandas()`.
I got the same number of passes, fails, and errors running `make test_no_spark` before and after adding the new code. 
The code is basically the same for all three classes and could possibly be abstracted away. But I'm not sure about your preferences there.
I haven't written a test because I wasn't sure about requirements and standards. If you give me some hints I will try to write some tests.

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Thanks for the PR @grofte ! Are you aware of this though? https://docs.kedro.org/en/stable/configuration/advanced_configuration.html#how-to-use-resolvers-in-the-omegaconfigloader

**Comment by grofte** [comment]
I will have a look, thank you.

**Comment by grofte** [comment]
Doh

```yaml
my_polars_dataset:
  type: polars.CSVDataset
  filepath: data/01_raw/my_dataset.csv
  load_args:
    dtypes:
      product_age: "${polars:Float64}"
      group_identifier: "${polars:Utf8}"
    try_parse_dates: true
```

**Comment by noklam** [comment]
@grofte Is this PR still relevant? custom resolver should be the default solution for non-primitive type.

**Comment by astrojuanlu** [comment]
Wondering: is there a way to ship a custom resolver with a plugin? So that users do `pip install kedro-datasets[polars]` and have the `$polars` resolver already available.

This is clearly the preferred option but I foresee this might become a common point of friction, maybe we can alleviate it somehow.

**Comment by grofte** [comment]
I'll delete it - definitely not relevant. 
Maybe I'll make a PR on the docstring to add a link to the stuff about the omega config loader. There's already a link in load arguments to Polars so I assume it would be okay to add?

**Comment by merelcht** [comment]
Hi @grofte are you still interested in doing something with this PR or can I close it?

**Comment by astrojuanlu** [comment]
Closing and opened https://github.com/kedro-org/kedro-plugins/issues/687

**Pull request closed without merging**
