### PR TITLE
build(datasets): fix typos in definition of extras

### PR DESCRIPTION
**Pull request by deepyaman**
## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by deepyaman — COMMENTED** [review]
Another question I had when looking through the file: Is it intentional that the extras for `pandas.GBQQueryDataset` and `pandas.GBQTableDataset` are lumped under `pandas-gbqdataset`, and the same for `pandas.SQLQueryDataset` and `pandas.SQLTableDataset` being lumped under `pandas-sqldataset`? I couldn't find any discussion on https://github.com/kedro-org/kedro-plugins/pull/570 at a glance, but it seemed inconsistent with how users usually install these based on dataset name.

**Comment by deepyaman** [comment]
Docs issue is unrelated, and I couldn't figure out how to resolve it at a glance.

**Comment by ankatiyar** [comment]
> Another question I had when looking through the file: Is it intentional that the extras for `pandas.GBQQueryDataset` and `pandas.GBQTableDataset` are lumped under `pandas-gbqdataset`, and the same for `pandas.SQLQueryDataset` and `pandas.SQLTableDataset` being lumped under `pandas-sqldataset`? I couldn't find any discussion on #570 at a glance, but it seemed inconsistent with how users usually install these based on dataset name.

No, I think I missed it while going by file names - fixed it in 16b084f6a876fc0ed5673d6d11e9e8c7b919af52

**Review by ankatiyar — APPROVED** [review]
Thanks @deepyaman!

**Review by astrojuanlu — APPROVED** [review]
Thanks @deepyaman !

**Pull request merged**
