### PR TITLE
fix(datasets): Unpin pandas gbq

### PR DESCRIPTION
**Pull request by felipemonroy**
## Description
More recent versions of pandas does not work with `pandas-gbq<0.18.0`, which was set for `python < 3.11` 

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by felipemonroy** [comment]
@ankatiyar @astrojuanlu @noklam could you help me re-running the tests please?

**Comment by astrojuanlu** [comment]
@felipemonroy Are you able to reproduce the test failures locally?

**Comment by felipemonroy** [comment]
@astrojuanlu I can't. I assume it is related to this issue https://github.com/kedro-org/kedro-plugins/issues/755. Right now, passing the tests requires a bit of luck.

**Comment by felipemonroy** [comment]
@astrojuanlu could you review again please?

**Review by astrojuanlu — APPROVED** [review]
LGTM!

**Review by noklam — APPROVED** [review]

**Comment by astrojuanlu** [comment]
Can't believe we managed to merge this finally 😅 thanks for your patience @felipemonroy !

**Pull request merged**
