### PR TITLE
build(airflow): Release 0.9.0 

### PR DESCRIPTION
**Pull request by SajidAlamQB**
## Description

Release `kedro-airflow` 0.9.0

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the relevant `RELEASE.md` file
- [x] Added tests to cover my changes

### CODE REVIEW

**Review by ankatiyar — APPROVED** [review]
🚀

**Comment by merelcht** [comment]
Let's get in https://github.com/kedro-org/kedro-plugins/pull/697 before the release. It's very minor so would be silly to do another release just for the link update.

**Review by astrojuanlu — APPROVED** [review]
🔥

**Review by DimedS — APPROVED** [review]
🚀

**Pull request merged**
