### PR TITLE
feat(airflow): make sure `kedro airflow create` is deterministic

### LINKED ISSUE #380: Deterministic `kedro-airflow` DAGs
## Description
The DAGs generated by `kedro-airflow` are not deterministic, as they are only topologically sorted.

## Context
As a user that version controls the DAGs, I would like to have a diff only when the DAG changes (the ordering of the edges does not).

Diff in Edges

_Avoiding situations where the diff consists only of edges ordered differently._

## Possible Implementation
Sort the edges deterministically in `kedro-airflow`

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

### PR DESCRIPTION
**Pull request by noklam**
## Description

Fix #380.

## Development notes

Sort the dependencies dictionaries to make sure it's deterministic.

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by noklam** [comment]
@sbrugman tagging you here since I cannot add you as reviewer.

**Review by ankatiyar — APPROVED** [review]
LGTM!

**Comment by sbrugman** [comment]
Nice work!

**Review by astrojuanlu — APPROVED** [review]
LGTM!

**Comment by sbrugman** [comment]
With the grouping of the nodes, we needed a slightly different data structure for storing the dependencies.
The same approach can be taken - adjusted to that structure - or we could sort in the jinja template

**Comment by noklam** [comment]
@sbrugman Thanks for the heads up, I guess this PR is not ready to be merged then. I will have to find some time to look at the group nodes later this week. If you are interested to take over feel free to do so.

**Comment by noklam** [comment]
@sbrugman Actually I think the current implementation works fine. I did a manual test that I run the same command 10times and diff, I checked the `dependencies` are different but the output DAG are the same. unit tests are tricky because for each python process the randomness is fixed.

I will leave this here for a few days, but if there are no objections I will merge this.

**Pull request merged**
