### PR TITLE
build(datasets): release 1.4.0

### PR DESCRIPTION
**Pull request by noklam**
## Description

doc fix release together with kedro 0.18.9 https://github.com/kedro-org/kedro/pull/2619
* Added `SparkStreamingDataSet`
- [x] https://github.com/kedro-org/kedro-plugins/pull/198
## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Approving if https://github.com/kedro-org/kedro/pull/2485 RTD build passes 😄 pointed it to this branch.

**Comment by noklam** [comment]
I am adding the streaming dataset to the release if nothing fails. That's huge 🔥

**Comment by astrojuanlu** [comment]
> I am adding the streaming dataset to the release if nothing fails. That's huge 🔥

Worth bumping to 1.4.0 then?

**Comment by noklam** [comment]
@astrojuanlu I think we only update when it's breaking? But I see your point bumping the version to signal the newly added features. I'll check again during stand-up tomorrow.

**Review by astrojuanlu — APPROVED** [review]
Worked https://kedro--2485.org.readthedocs.build/en/2485/kedro_datasets.html ⭐

**Review by merelcht — APPROVED** [review]
🎉

**Pull request merged**
