### PR TITLE
fix: backwards compatibility for `kedro-airflow`

### PR DESCRIPTION
**Pull request by sbrugman**
## Description
Closes https://github.com/kedro-org/kedro-plugins/issues/321
Classified as `fix` as the `pyproject.toml` specifies that the plugin is compatible with Kedro 0.17.5, which without this fix it is not.

## Development notes
Tested with internal setup.

## Checklist

- [X] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [X] Updated the documentation to reflect the code changes
- [X] Added a description of this change in the relevant `RELEASE.md` file
- [X] Added tests to cover my changes

### CODE REVIEW

**Comment by ankatiyar** [comment]
@sbrugman Thank you for the quick PR! I think this fix looks good but it also needs a test to satisfy 100% code coverage. Could you add that too?

**Comment by sbrugman** [comment]
> @sbrugman Thank you for the quick PR! I think this fix looks good but it also needs a test to satisfy 100% code coverage. Could you add that too? + I think the commits need to be signed off

Added a test (now the coverage is 100% again) and signed off the commits

**Review by merelcht — APPROVED** [review]
Thanks for this fix @sbrugman ! 👍

**Review by ankatiyar — APPROVED** [review]
Thank you @sbrugman!

**Pull request merged**
