### PR TITLE
feat: Adding preview support to yaml datasets

### PR DESCRIPTION
**Pull request by derluke**
## Description
Support preview of YAML datasets in kedro viz

## Development notes
Simple implementation

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by derluke** [comment]
Looks like there was a timeout with the readthedocs check

**Comment by DimedS** [comment]
@derluke thanks for that! I will review it today, @jitu5 do you have a capacity to review it also?

**Review by DimedS — APPROVED** [review]
Thank you for the PR, @derluke! It works well on my end!

**Comment by derluke** [comment]
It looks as if something in main broke the tests. I assume the tests themselves are broken, correct?

**Comment by ankatiyar** [comment]
@derluke the failures are unrelated to your PR, I'll get your PR merged as soon as we solve the CI issues 😁

**Review by jitu5 — APPROVED** [review]

**Comment by ankatiyar** [comment]
FYI: I added a fix for the CI issue and this change to the release notes!

**Pull request merged**
