### PR TITLE
fix: airflow metadata

### PR DESCRIPTION
**Pull request by AhdraMeraliQB**
## Description

Fix failing airflow build: https://github.com/kedro-org/kedro-plugins/issues/494
Tests blocking https://github.com/kedro-org/kedro/pull/3462

## Development notes

Instead of calling cookiecutter directly, the test setup has been changed to use `kedro new` (not unlike the existing kedro-docker e2e setup), without introducing new dependencies, and eliminating the direct reliance of kedro-plugins on on cookiecutter.

Honestly, still unsure why `cookiecutter()` would fail but `cookiecutter` wrapped in `kedro new` is fine 🤔. It looks like the original fixture was copied over from kedro-mlflow, might 0.19.0 be breaking there?

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by noklam** [comment]
< However, pyproject.toml is not found when an airflow project is generated, hence trying to remove requirements from a non-existent file causes errors.

How was this airflow project generated? Is it the `kedro-starter` starters?

**Comment by AhdraMeraliQB** [comment]
CC: @noklam 
> < However, pyproject.toml is not found when an airflow project is generated, hence trying to remove requirements from a non-existent file causes errors.
> 
> How was this airflow project generated? Is it the `kedro-starter` starters?

It uses a link to the kedro template in framework's `kedro/templates/project`

**Review by DimedS — APPROVED** [review]
Thank you, @AhdraMeraliQB , it's a great work! I agree that it's more clear to use common testing pattern with 'kedro new' instead of manually use cookiecutter.

**Review by SajidAlamQB — APPROVED** [review]
This implementation makes sense, but I'm wondering why the original fixture didn't work are we just missing the tools and example fields? But happy to go with this 👍

**Comment by AhdraMeraliQB** [comment]
@SajidAlamQB Unsure, maybe @ankatiyar can shed some light on this when she's back. Ultimately I do think using kedro new instead of cookiecutter aligns more closely with the rest of our testing practices, but it is odd that it resolved that particular issue.

**Pull request merged**
