### PR TITLE
chores: Create issue_metrics github action

### PR DESCRIPTION
**Pull request by noklam**
## Description

https://github.com/github/issue-metrics

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Framework counterpart: https://github.com/kedro-org/kedro/pull/2814

**Comment by noklam** [comment]
Maybe we can explore do both repositories in one go, it may requires lifted permission though.

**Comment by merelcht** [comment]
@noklam Do you still want to complete this?

**Comment by noklam** [comment]
Closing as we are not using this in a meaningful way for the other repo, I can resume this if we end up found this useful.

**Pull request closed without merging**
