### PR TITLE
refactor: remove unused imports

### PR DESCRIPTION
**Pull request by sbrugman**
## Description
Removed unused imports in `kedro-airflow` template

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by noklam — APPROVED** [review]
Thanks for spotting this!

**Comment by noklam** [comment]
I guess it doesn't run on non python file?

**Review by astrojuanlu — APPROVED** [review]
LGTM, thanks @sbrugman! Could you please amend your commits with a signoff to make the DCO check happy?

**Comment by sbrugman** [comment]
Added the signoff. Indeed, the linter doesn't run on jinja

**Comment by astrojuanlu** [comment]
cc @ankatiyar about CircleCI

**Comment by ankatiyar** [comment]
Should be fine now @astrojuanlu 😄

**Pull request merged**
