### PR TITLE
fix: TF model load failure when model is saved as a TensorFlow Saved Model format

### PR DESCRIPTION
**Pull request by Edouard59**
## Description
when a model is saved in the TensorFlow SavedModel format ("tf" default option in tf.save_model when using TF 2.x) via the catalog.xml file, the subsequent loading of that model for further use in a subsequent node fails. The issue is linked to the fact that the model files don't get copied into the temporary folder, presumably because the _fs.get function "thinks" that the provided path is a file and not a folder.

## Development notes
Adding an terminating "/" to the path fixes the issue. This has been tested with the following catalog.yml entry to validate that the fix works:

"model_trained_experiment0":
  type: tensorflow.TensorFlowModelDataset
  filepath: data/06_models/experiment0/model/

This together with a pipeline made of a node outputting "model_trained_experiment0" and a subsequent node inputting "model_trained_experiment0"

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Hello @Edouard59, thanks a lot for this pull request! I noticed you didn't add a regression test for it - it's fine, but could you share the error that you were observing before, with the full traceback if possible? I'm thinking that maybe this is related to https://github.com/kedro-org/kedro-plugins/issues/359 cc @ryansaxe 

Also, this has a couple of style checks failing, could you please look into fixing those?

**Comment by Edouard59** [comment]
@astrojuanlu: Hello, here is the full trace back of the error:

─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/io/core.py:19 │
│ 3 in load                                                                                        │
│                                                                                                  │
│   190 │   │   self._logger.debug("Loading %s", str(self))                                        │
│   191 │   │                                                                                      │
│   192 │   │   try:                                                                               │
│ ❱ 193 │   │   │   return self._load()                                                            │
│   194 │   │   except DatasetError:                                                               │
│   195 │   │   │   raise                                                                          │
│   196 │   │   except Exception as exc:                                                           │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro_datasets/tens │
│ orflow/tensorflow_model_dataset.py:147 in _load                                                  │
│                                                                                                  │
│   144 │   │   │   │   with tf.device(device_name):                                               │
│   145 │   │   │   │   │   model = tf.keras.models.load_model(path, **self._load_args)            │
│   146 │   │   │   else:                                                                          │
│ ❱ 147 │   │   │   │   model = tf.keras.models.load_model(path, **self._load_args)                │
│   148 │   │   │   return model                                                                   │
│   149 │                                                                                          │
│   150 │   def _save(self, data: tf.keras.Model) -> None:                                         │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/keras/utils/traceba │
│ ck_utils.py:67 in error_handler                                                                  │
│                                                                                                  │
│    64 │     return fn(*args, **kwargs)                                                           │
│    65 │   except Exception as e:  # pylint: disable=broad-except                                 │
│    66 │     filtered_tb = _process_traceback_frames(e.__traceback__)                             │
│ ❱  67 │     raise e.with_traceback(filtered_tb) from None                                        │
│    68 │   finally:                                                                               │
│    69 │     del filtered_tb                                                                      │
│    70                                                                                            │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/tensorflow/python/s │
│ aved_model/loader_impl.py:115 in parse_saved_model                                               │
│                                                                                                  │
│   112 │   except text_format.ParseError as e:                                                    │
│   113 │     raise IOError(f"Cannot parse file {path_to_pbtxt}: {str(e)}.")                       │
│   114   else:                                                                                    │
│ ❱ 115 │   raise IOError(                                                                         │
│   116 │   │   f"SavedModel file does not exist at: {export_dir}{os.path.sep}"                    │
│   117 │   │   f"{{{constants.SAVED_MODEL_FILENAME_PBTXT}|"                                       │
│   118 │   │   f"{constants.SAVED_MODEL_FILENAME_PB}}}")                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: SavedModel file does not exist at: /tmp/kedro_tensorflow_tmpga9447ts/{saved_model.pbtxt|saved_model.pb}

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/bin/kedro:8 in <module>                          │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/framework/cli │
│ /cli.py:211 in main                                                                              │
│                                                                                                  │
│   208 │   """                                                                                    │
│   209 │   _init_plugins()                                                                        │
│   210 │   cli_collection = KedroCLI(project_path=Path.cwd())                                     │
│ ❱ 211 │   cli_collection()                                                                       │
│   212                                                                                            │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/click/core.py:1157  │
│ in __call__                                                                                      │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/framework/cli │
│ /cli.py:139 in main                                                                              │
│                                                                                                  │
│   136 │   │   )                                                                                  │
│   137 │   │                                                                                      │
│   138 │   │   try:                                                                               │
│ ❱ 139 │   │   │   super().main(                                                                  │
│   140 │   │   │   │   args=args,                                                                 │
│   141 │   │   │   │   prog_name=prog_name,                                                       │
│   142 │   │   │   │   complete_var=complete_var,                                                 │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/click/core.py:1078  │
│ in main                                                                                          │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/click/core.py:1688  │
│ in invoke                                                                                        │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/click/core.py:1434  │
│ in invoke                                                                                        │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/click/core.py:783   │
│ in invoke                                                                                        │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/framework/cli │
│ /project.py:453 in run                                                                           │
│                                                                                                  │
│   450 │   with KedroSession.create(                                                              │
│   451 │   │   env=env, conf_source=conf_source, extra_params=params                              │
│   452 │   ) as session:                                                                          │
│ ❱ 453 │   │   session.run(                                                                       │
│   454 │   │   │   tags=tag,                                                                      │
│   455 │   │   │   runner=runner(is_async=is_async),                                              │
│   456 │   │   │   node_names=node_names,                                                         │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/framework/ses │
│ sion/session.py:436 in run                                                                       │
│                                                                                                  │
│   433 │   │   )                                                                                  │
│   434 │   │                                                                                      │
│   435 │   │   try:                                                                               │
│ ❱ 436 │   │   │   run_result = runner.run(                                                       │
│   437 │   │   │   │   filtered_pipeline, catalog, hook_manager, session_id                       │
│   438 │   │   │   )                                                                              │
│   439 │   │   │   self._run_called = True                                                        │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/runner/runner │
│ .py:103 in run                                                                                   │
│                                                                                                  │
│   100 │   │   │   self._logger.info(                                                             │
│   101 │   │   │   │   "Asynchronous mode is enabled for loading and saving data"                 │
│   102 │   │   │   )                                                                              │
│ ❱ 103 │   │   self._run(pipeline, catalog, hook_manager, session_id)                             │
│   104 │   │                                                                                      │
│   105 │   │   self._logger.info("Pipeline execution completed successfully.")                    │
│   106                                                                                            │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/runner/sequen │
│ tial_runner.py:70 in _run                                                                        │
│                                                                                                  │
│   67 │   │                                                                                       │
│   68 │   │   for exec_index, node in enumerate(nodes):                                           │
│   69 │   │   │   try:                                                                            │
│ ❱ 70 │   │   │   │   run_node(node, catalog, hook_manager, self._is_async, session_id)           │
│   71 │   │   │   │   done_nodes.add(node)                                                        │
│   72 │   │   │   except Exception:                                                               │
│   73 │   │   │   │   self._suggest_resume_scenario(pipeline, done_nodes, catalog)                │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/runner/runner │
│ .py:331 in run_node                                                                              │
│                                                                                                  │
│   328 │   if is_async:                                                                           │
│   329 │   │   node = _run_node_async(node, catalog, hook_manager, session_id)                    │
│   330 │   else:                                                                                  │
│ ❱ 331 │   │   node = _run_node_sequential(node, catalog, hook_manager, session_id)               │
│   332 │                                                                                          │
│   333 │   for name in node.confirms:                                                             │
│   334 │   │   catalog.confirm(name)                                                              │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/runner/runner │
│ .py:414 in _run_node_sequential                                                                  │
│                                                                                                  │
│   411 │                                                                                          │
│   412 │   for name in node.inputs:                                                               │
│   413 │   │   hook_manager.hook.before_dataset_loaded(dataset_name=name, node=node)              │
│ ❱ 414 │   │   inputs[name] = catalog.load(name)                                                  │
│   415 │   │   hook_manager.hook.after_dataset_loaded(                                            │
│   416 │   │   │   dataset_name=name, data=inputs[name], node=node                                │
│   417 │   │   )                                                                                  │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/io/data_catal │
│ og.py:506 in load                                                                                │
│                                                                                                  │
│   503 │   │   │   "Loading data from '%s' (%s)...", name, type(dataset).__name__                 │
│   504 │   │   )                                                                                  │
│   505 │   │                                                                                      │
│ ❱ 506 │   │   result = dataset.load()                                                            │
│   507 │   │                                                                                      │
│   508 │   │   return result                                                                      │
│   509                                                                                            │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/io/core.py:61 │
│ 4 in load                                                                                        │
│                                                                                                  │
│   611 │   │   return self._filepath / version / self._filepath.name                              │
│   612 │                                                                                          │
│   613 │   def load(self) -> _DO:  # noqa: useless-parent-delegation                              │
│ ❱ 614 │   │   return super().load()                                                              │
│   615 │                                                                                          │
│   616 │   def save(self, data: _DI) -> None:                                                     │
│   617 │   │   self._version_cache.clear()                                                        │
│                                                                                                  │
│ /home/scioteq/miniconda3/envs/HandwrittenDigits/lib/python3.10/site-packages/kedro/io/core.py:20 │
│ 2 in load                                                                                        │
│                                                                                                  │
│   199 │   │   │   message = (                                                                    │
│   200 │   │   │   │   f"Failed while loading data from data set {str(self)}.\n{str(exc)}"        │
│   201 │   │   │   )                                                                              │
│ ❱ 202 │   │   │   raise DatasetError(message) from exc                                           │
│   203 │                                                                                          │
│   204 │   def save(self, data: _DI) -> None:                                                     │
│   205 │   │   """Saves data by delegation to the provided save method.                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
DatasetError: Failed while loading data from data set 
TensorFlowModelDataset(filepath=/home/scioteq/handwrittendigits/data/06_models/experiment0/model, load_args={}, protocol=file, 
save_args={'save_format': tf}).
SavedModel file does not exist at: /tmp/kedro_tensorflow_tmpga9447ts/{saved_model.pbtxt|saved_model.pb}

**Comment by astrojuanlu** [comment]
I confirm this fixes https://github.com/kedro-org/kedro-plugins/issues/359 🎉 

> One is I guess because I didn't add a keyword like "fix:" in the commit title ? I'm not quite sure how to update the commit title...

You already edited the PR title, thanks!

> As for the lint error, it says "black" failed, I have no clue what that means... sorry...

No worries! You can try to do `pip install "ruff~=0.0.290" "black~=22.0" && make lint plugin=kedro-datasets` and commit the result.

**Review by ankatiyar — APPROVED** [review]
This could go under bug fixes in the release notes! Thanks @Edouard59 💯

**Review by merelcht — APPROVED** [review]
Thanks for fixing this @Edouard59 ! Don't forget to add this fix as well as your name to the contributors in the release notes 🙂

**Comment by Edouard59** [comment]
@merelcht How do I add the fix and my name to the contributors in the release notes ? Where are the release notes ? (sorry for my newbie questions ;)

**Comment by ankatiyar** [comment]
I can do it for you @Edouard59

**Pull request merged**
