### PR TITLE
feat(datasets): Add format for ImageDataSet save

### PR DESCRIPTION
**Pull request by daniel-falk**
When using the ImageDataSet with S3 storage you need to manually specify the format in the save_args dict despite the suffix in the file. This is since the save method on the PIL images are called with an open file. The PIL documentation states the following about the format argument:

"If a file object was used instead of a filename, this parameter should always be used."

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by merelcht** [comment]
Hi @daniel-falk, thanks for opening this PR and sorry for the late response. Are you still working on this or is it ready for review? At the moment the builds are all broken, but it could be that merging `main` in again will fix that.

**Comment by daniel-falk** [comment]
Thanks @merelcht ! I rebased to latest main and pushed. I think it is all done and ready for review, I will just make sure it passes the tests.

**Comment by daniel-falk** [comment]
Hi, sorry for the delay! My time has been very limited lately, I'll try to make some time for this but I'm not sure it will be possible right now.

**Comment by ankatiyar** [comment]
Hi @daniel-falk, this is pretty good but this PR has been open for a while. :) 
I hope you don't mind my taking over this. It was just missing a unit-test to satisfy the code coverage requirement which I've added now. It'd be nice to get this merged in!

**Comment by daniel-falk** [comment]
Thank you very much @ankatiyar ! I have been feeling bad for not fixing this, so I am super happy you took it the last mile!

**Review by astrojuanlu — APPROVED** [review]
I didn’t realise this was so close, thanks @daniel-falk and @ankatiyar!

**Review by SajidAlamQB — APPROVED** [review]
Thank you @daniel-falk and @ankatiyar! 🌟

**Pull request merged**
