### PR TITLE
docs(datasets): fix typo in Markdown

### PR DESCRIPTION
**Pull request by sbrugman**
## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
Thanks @sbrugman! If you have a moment, could you signoff the commit to make the DCO check happy?

**Review by deepyaman — APPROVED** [review]
Nice catch! LGTM

**Comment by astrojuanlu** [comment]
Waiting on https://github.com/kedro-org/kedro/pull/2673

**Comment by noklam** [comment]
Update the branch and see if it can be merged now.

**Comment by noklam** [comment]
@deepyaman The Validate PR title checks is failing with TOKEN, do you know why is it because it is from a fork PR ?

**Review by noklam — APPROVED** [review]

**Comment by sbrugman** [comment]
Rebased the PR

**Comment by astrojuanlu** [comment]
One would say it should be easier to fix a typo... Sorry for dragging this @sbrugman.

We spotted the `Error: Resource not accessible by integration` error earlier today. Still working on a solution.

**Comment by astrojuanlu** [comment]
Thanks @sbrugman 🙏🏽

**Pull request merged**
