### PR TITLE
docs: Add python version support policy to plugin `README.md`s

### LINKED ISSUE #404: Document and apply Python version support policy for all plugins
## Description
In https://github.com/kedro-org/kedro/issues/2815 we agreed to

- Adopt [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) for `kedro-datasets`
- In the absence of a stricter policy for the rest of the plugins, we treat removing Python version support as non-breaking when it's no longer officially supported (see https://devguide.python.org/versions/)

Python versions support chart

We should put this policy into practice by

- Dropping Python 3.8 support in `kedro-datasets` ASAP, hence in the next breaking release (end of NEP 29 window as of Apr 14, 2023)
- Dropping Python 3.8 support for the rest of the plugins in October 2024

### PR DESCRIPTION
**Pull request by merelcht**
## Description
Closed #404 

## Development notes

- Added the python version policy to the `README.md` files of each plugin
- Added licence/contributing info to plugins where it was missing.

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Updated the documentation to reflect the code changes
- [ ] Added a description of this change in the relevant `RELEASE.md` file
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by astrojuanlu — APPROVED** [review]
💯

**Review by stichbury — APPROVED** [review]

**Comment by merelcht** [comment]
@astrojuanlu Did you mean to already merge this? The builds were still running

**Comment by astrojuanlu** [comment]
😳 I enabled the automerge and in fact the gatekeeper is already green

**Comment by astrojuanlu** [comment]
image

unsure why this happened, but yeah I didn't intend to merge before running all the jobs, sorry 🙏🏽

**Comment by merelcht** [comment]
> 😳 I enabled the automerge and in fact the gatekeeper is already green

Hmmm it looks like the merge gatekeeper only tracked part of the builds: https://github.com/kedro-org/kedro-plugins/actions/runs/6735475912/job/18308735307 🤔

**Pull request merged**
