### PR TITLE
fix(datasets): Don't warn for SparkDataset on Databricks when using s3

### PR DESCRIPTION
**Pull request by alamastor**
## Description
Fix for #319 

## Development notes
I've implemented the fix for `s3`, `s3a`, `s3n`. If there's protocols I should add for Azure, GCP or others, let me know - I don't have experience with these and couldn't find the protocols to use, if they exist.

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the relevant `RELEASE.md` file
- [x] Added tests to cover my changes

### CODE REVIEW

**Comment by noklam** [comment]
@alamastor Thanks for the PR! I think we can reuse the existing [`CLOUD_PROTOCOLS`](https://github.com/kedro-org/kedro/blob/2f76e7fdf47b0b8a6840b9c9ad19d61897daf0da/kedro/io/core.py#L30).

The point here is that we should only raise error when it's a local path. Maybe there are more direct ways, otherwise we can keep your logic that if it's not DBFS and not in the known protocols, then we raise the error.

**Comment by alamastor** [comment]
Thanks @noklam, that makes sense. If we want to check it's local path, I could just check that `://` is not in the path. Or I could reuse `CLOUD_PROTOCOLS`, in that case I think it would be nice to update `_split_filepath` to return the protocol name without `://`, so it works easily with `CLOUD_PROTOCOLS`, and update other uses of `fs_prefix`. What do you think?

**Comment by noklam** [comment]
@alamastor I think it may break quite a few things, `_split_filepath` is rather special due to Spark & databricks. In `kedro`, there is a function that used extensively in most versioned datasets.

https://github.com/kedro-org/kedro/blob/3d41425c39ff061809f2febb87994d787f03bf4d/kedro/io/core.py#L668-L679

There are also few reasons we shouldn't do this:
- The protocol definition is from `urllib` (more or less standard), I don't want to introduce confusion here.
- The protocol need to be the same as `fsspec` (abstract of filesystem, the library that we used in Kedro to load file from remote storage). Internally we fork some function from fsspec to fix some bug historically. 

Do you think you can make it work without changing the `CLOUD_PROTOCOL` definition?

**Comment by alamastor** [comment]
@noklam, I went with a simpler approach. Does that look ok?

**Comment by noklam** [comment]
I am on PTO now, will have a look as soon as I back to work 🙏

**Review by noklam — APPROVED** [review]
Thank you for the PR, looks good :)

**Review by merelcht — APPROVED** [review]
Thanks for the contribution @alamastor 👍 ⭐

**Pull request merged**
