### PR TITLE
feat(airflow): include environment name in DAG filename

### PR DESCRIPTION
**Pull request by sbrugman**
## Description
Closes https://github.com/kedro-org/kedro-plugins/issues/487

## Checklist

- [X] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [X] Updated the documentation to reflect the code changes
- [x] Added a description of this change in the relevant `RELEASE.md` file
- [X] Added tests to cover my changes

### CODE REVIEW

**Comment by sbrugman** [comment]
The test fail at cookiecutter breaking.

**Comment by sbrugman** [comment]
@noklam Merged with main, should be good to go now. Very simple change!

**Comment by sbrugman** [comment]
Resolved the merge conflict after merging #241

**Review by noklam — COMMENTED** [review]
Nice change, slightly nit picking.

Can we use `DEFAULT_RUN_ENV` and `DEFAULT_PIPELINE`? I found `ENV_DEFAULT` slightly confusing, `default_run_env` is what we have in kedro/config.py so I prefer to keep the terminology consistent.

**Review by merelcht — APPROVED** [review]
LGTM! Thanks @sbrugman ⭐

**Review by ankatiyar — APPROVED** [review]
Thanks @sbrugman!

**Pull request merged**
